
original_source_code := "qsort_mt_orig.c"
source_code := "qsort_mt.c"
original_exe := "qsort"
exe := "qsort_futex"
cflags := "-Wall -g -O2 -D_GNU_SOURCE -fsanitize=thread -lpthread"

@build:
    gcc -o {{original_exe}} {{original_source_code}} {{cflags}}
    gcc -o {{exe}} {{source_code}} {{cflags}}

@thread-sanitizer:
    clang {{source_code}} -fsanitize=thread -fPIE -pie -g -o {{exe}}
    ./{{exe}}

@clean:
    rm -f {{exe}}
    rm -f perf.data*

# --------
#   perf
# ref: https://www.brendangregg.com/perf.html
# --------

@perf-annotate:
    perf annotate

@perf-report:
    perf report

@perf-record:
    perf record ./{{exe}}

@perf-stat:
    perf stat ./{{exe}}
